[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.71"
flutter_rust_bridge = "1.78.0"
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
moksha-wallet = { path = "../../moksha-wallet" }
moksha-core = { path = "../../moksha-core" }
moksha-fedimint = { path = "../../moksha-fedimint" }
lazy_static = "1.4.0"
reqwest = {version= "0.11.18", features = ["serde_json","json","rustls-tls"], default-features = false}


[dev-dependencies]
tempfile = "3.6.0"

